services:
  - type: web
    name: my-react-app
    env: static
    staticPublishPath: build
    buildCommand: npm run build
    startCommand: serve -s build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
